# Generated by Django 6.0.6 on 2026-07-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
