import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, RobustScaler, OneHotEncoder, OrdinalEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.base import BaseEstimator, TransformerMixin

class DatetimeExtractor(BaseEstimator, TransformerMixin):
    """
    Custom scikit-learn transformer to extract year, month, day, day_of_week from datetime columns.
    """
    def __init__(self):
        pass
        
    def fit(self, X, y=None):
        return self
        
    def transform(self, X):
        X_df = pd.DataFrame(X)
        out = pd.DataFrame(index=X_df.index)
        
        for col in X_df.columns:
            # Safely convert to datetime
            dt_series = pd.to_datetime(X_df[col], errors='coerce')
            out[f"{col}_year"] = dt_series.dt.year.fillna(0)
            out[f"{col}_month"] = dt_series.dt.month.fillna(0)
            out[f"{col}_day"] = dt_series.dt.day.fillna(0)
            out[f"{col}_dayofweek"] = dt_series.dt.dayofweek.fillna(0)
            
        return out.values

class PipelineBuilder:
    """
    Converts a JSON preprocessing plan generated by PreprocessingRecommendationEngine
    into an executable scikit-learn ColumnTransformer.
    """
    
    def __init__(self, plan: dict):
        self.plan = plan
        
    def build_pipeline(self) -> ColumnTransformer:
        transformers = []
        
        # We need to build a pipeline for each column based on its plan
        for col_name, rules in self.plan.items():
            if rules.get("action") == "exclude" or rules.get("type") == "target":
                continue
                
            steps = []
            
            # 1. Missing Value Imputation
            missing_strategy = rules.get("missing", "none")
            if missing_strategy == "median":
                steps.append(("imputer", SimpleImputer(strategy="median")))
            elif missing_strategy == "most_frequent":
                steps.append(("imputer", SimpleImputer(strategy="most_frequent")))
                
            # 2. Encoding / Feature Engineering
            col_type = rules.get("type")
            if col_type == "datetime":
                steps.append(("datetime_extractor", DatetimeExtractor()))
                # Extracted features are numeric, we can scale them if we want, but standard is fine
                steps.append(("scaler", StandardScaler()))
                
            elif col_type == "text":
                # TfidfVectorizer expects 1D array or list of strings. ColumnTransformer passes 2D for single col unless we use a wrapper.
                # Since we are putting it in a Pipeline, we need a custom wrapper or we just map it.
                # A simpler way is to not put it in a Pipeline here, but directly into ColumnTransformer if it's the only step.
                # However, if there are missing values, TfidfVectorizer fails on np.nan.
                pass # Text will be handled specially below
                
            else:
                encoding_strategy = rules.get("encoding", "none")
                if encoding_strategy == "one_hot":
                    steps.append(("encoder", OneHotEncoder(handle_unknown="ignore", sparse_output=False)))
                elif encoding_strategy in ["ordinal", "target"]:
                    # Using OrdinalEncoder for high cardinality as a safe fallback in standard sklearn
                    steps.append(("encoder", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1)))
                    
                # 3. Scaling (Numerical usually)
                scaling_strategy = rules.get("scaling", "none")
                if scaling_strategy == "standard":
                    steps.append(("scaler", StandardScaler()))
                elif scaling_strategy == "robust":
                    steps.append(("scaler", RobustScaler()))
                    
            if col_type == "text":
                # Special handling for text: TfidfVectorizer
                # We need to ensure it gets a 1D array.
                class TextWrapper(BaseEstimator, TransformerMixin):
                    def __init__(self, vectorizer):
                        self.vectorizer = vectorizer
                    def fit(self, X, y=None):
                        self.vectorizer.fit(np.ravel(X).astype(str))
                        return self
                    def transform(self, X):
                        return self.vectorizer.transform(np.ravel(X).astype(str)).toarray()
                        
                steps.append(("imputer", SimpleImputer(strategy="constant", fill_value="")))
                steps.append(("tfidf", TextWrapper(TfidfVectorizer(max_features=100))))

            if steps:
                transformers.append((f"pipe_{col_name}", Pipeline(steps), [col_name]))
                
        # If no features remain (e.g. all excluded), this will raise an error on fit.
        # It's up to the caller to ensure there are valid features.
        preprocessor = ColumnTransformer(transformers=transformers, remainder="drop")
        return preprocessor
