import logging

logger = logging.getLogger(__name__)

class TargetDetectionEngine:
    """
    Intelligent engine to detect, score, and rank potential target columns
    based on the JSON profile generated by DatasetProfiler.
    """
    def __init__(self, dataset_profile: dict):
        self.profile = dataset_profile
        self.dataset_meta = self.profile.get("dataset", {})
        self.columns_meta = self.profile.get("columns", {})
        
        # Heuristic keywords for naming convention scoring
        self.strong_target_keywords = ['target', 'label', 'class', 'outcome', 'response', 'prediction', 'result', 'churn', 'price', 'salary']
        self.weak_target_keywords = ['status', 'value', 'amount', 'y']
        
        # ID keywords for penalty
        self.id_keywords = ['customer_id', 'user_id', 'transaction_id', 'uuid', 'guid', 'id', 'index', 'hash']
        
    def detect_targets(self) -> list:
        candidates = []
        columns = list(self.columns_meta.keys())
        
        if not columns:
            return candidates
            
        for idx, col_name in enumerate(columns):
            col_meta = self.columns_meta[col_name]
            score, reasons, leakage = self._score_column(col_name, col_meta, idx, len(columns))
            
            # Filter out completely invalid targets
            if score < 0 or col_meta.get("unique_count", 0) <= 1 or col_meta.get("missing_pct", 0) > 80:
                continue
                
            problem_type = self.determine_problem_type(col_name)
            
            # Map numeric score to High/Medium/Low confidence
            if score >= 60:
                confidence = "High"
            elif score >= 30:
                confidence = "Medium"
            else:
                confidence = "Low"
                
            candidates.append({
                "column": col_name,
                "score": score,
                "confidence": confidence,
                "reasons": reasons,
                "leakage_warning": leakage,
                "detected_type": problem_type
            })
            
        # Sort candidates by score descending
        candidates.sort(key=lambda x: x["score"], reverse=True)
        return candidates
        
    def determine_problem_type(self, col_name: str) -> str:
        col_meta = self.columns_meta.get(col_name, {})
        inferred_type = col_meta.get("inferred_type", "categorical")
        unique_count = col_meta.get("unique_count", 0)
        
        if inferred_type == "numeric":
            # If numeric but very few unique values, could be classification
            if unique_count <= 20:
                return "Classification"
            # If it's floats, it's regression
            if "float" in col_meta.get("pandas_dtype", "").lower():
                return "Regression"
            return "Regression"
        else:
            return "Classification"
            
    def _score_column(self, col_name: str, col_meta: dict, position_idx: int, total_columns: int) -> tuple:
        score = 0
        reasons = []
        leakage = False
        
        col_lower = col_name.lower()
        inferred_type = col_meta.get("inferred_type", "categorical")
        unique_count = col_meta.get("unique_count", 0)
        unique_pct = col_meta.get("unique_pct", 0.0)
        
        # 1. Identifier Penalty
        is_id = col_meta.get("is_identifier", False)
        if is_id or any(kw in col_lower for kw in self.id_keywords) or (unique_pct > 95 and inferred_type in ['numeric', 'text']):
            # It's an ID. Targets are almost never IDs.
            return -100, ["Column is highly unique and appears to be an identifier."], False
            
        # 2. Text / Datetime exclusion
        if inferred_type in ['text', 'datetime']:
            return -50, [f"Column is of type {inferred_type} which is generally not a valid target."], False
            
        # 3. Naming Conventions
        if any(kw in col_lower for kw in self.strong_target_keywords):
            score += 40
            reasons.append("Target-like naming convention")
        elif any(kw == col_lower for kw in self.weak_target_keywords):
            score += 20
            reasons.append("Possible target naming convention")
            
        # 4. Cardinality & Data Type
        if inferred_type == "boolean" or unique_count == 2:
            score += 35
            reasons.append("Binary categorical target")
        elif inferred_type == "categorical":
            if 2 < unique_count <= 20:
                score += 30
                reasons.append("Multi-class categorical target")
            elif unique_count > 20:
                # High cardinality categoricals are generally poor targets unless it's a huge dataset
                score -= 10
                reasons.append("High cardinality categorical (may be hard to predict)")
        elif inferred_type == "numeric":
            if 2 < unique_count <= 20:
                score += 25
                reasons.append("Low-cardinality numeric (Classification)")
            else:
                score += 30
                reasons.append("Continuous numerical target (Regression)")
                
        # 5. Position
        if position_idx == total_columns - 1:
            score += 15
            reasons.append("Located at the end of the dataset")
            
        # 6. Leakage Detection (Heuristic)
        # If the column name contains "post", "after", "future" or is perfectly correlated with something
        if any(leak in col_lower for leak in ['post_', '_after', 'future']):
            leakage = True
            reasons.append("Warning: Potential data leakage detected from naming.")
            
        return score, reasons, leakage
