# Generated by Django 6.0.6 on 2026-08-15 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('PROFILE_DATASET', 'Profile Dataset'), ('TRAIN_MODEL', 'Train Model'), ('GENERATE_PIPELINE', 'Generate Pipeline')], max_length=50)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROFILING', 'Profiling'), ('AI_ANALYSIS', 'AI Analysis'), ('PREPROCESSING', 'Preprocessing'), ('TRAINING', 'Training'), ('OPTIMIZATION', 'Optimization'), ('EVALUATION', 'Evaluation'), ('PIPELINE_GENERATION', 'Pipeline Generation'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('current_stage', models.CharField(blank=True, max_length=255, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='datasets.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
