# Generated by Django 6.0.6 on 2026-09-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mljob',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATING', 'Validating'), ('PROFILING', 'Profiling'), ('WAITING_FOR_TARGET', 'Waiting for Target'), ('TARGET_CONFIRMED', 'Target Confirmed'), ('PREPROCESSING_PLAN', 'Preprocessing Plan'), ('WAITING_FOR_REVIEW', 'Waiting for Review'), ('TRAINING', 'Training'), ('EVALUATING', 'Evaluating'), ('EXPLAINING', 'Explaining'), ('EXPORTING', 'Exporting'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='UPLOADED', max_length=50),
        ),
    ]
